use_frameworks!

platform :ios, '10.0'

target 'IMLibCore_Example' do
  pod 'IMLibCore', :path => '../'

  target 'IMLibCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
